public class Main {
    public static void main(String[] args) {
        container myFrame = new container();
        String[] listOfCountries={"Afganistán",
                "Australia",
                "Bangladesh",
                "Bhután",
                "Brunei Darussalam",
                "Camboya",
                "China",
                "Fiji",
                "Filipinas",
                "India",
                "Indonesia",
                "Islas Cook",
                "Islas Marshall",
                "Islas Salomón",
                "Japón",
                "Kiribati",
                "Malasia",
                "Maldivas",
                "Micronesia",
                "Mongolia",
                "Myanmar",
                "Nauru",
                "Nepal",
                "Nueva Zelandia",
                "Pakistán",
                "Palau",
                "Papua Nueva Guinea",
                "República de Corea",
                "República Democrática Popular Lao",
                "República Popular Democrática de Corea",
                "Samoa",
                "Singapur",
                "Sri Lanka",
                "Tailandia",
                "Timor-Leste",
                "Tonga",
                "Tuvalu",
                "Vanuatu",
                "Vietnam",
                "Albania",
                "Alemania",
                "Andorra",
                "Armenia",
                "Austria",
                "Azerbaiyán",
                "Belarús",
                "Bélgica",
                "Bosnia y Herzegovina",
                "Bulgaria",
                "Chequia",
                "Chipre",
                "Croacia",
                "Dinamarca",
                "Eslovaquia",
                "Eslovenia",
                "España",
                "Estonia",
                "Federación de Rusia",
                "Finlandia",
                "Francia",
                "Georgia",
                "Grecia",
                "Hungría",
                "Irlanda",
                "Islandia",
                "Italia",
                "Kazajstán",
                "Kirguistán",
                "Letonia",
                "Liechtenstein",
                "Lituania",
                "Luxemburgo",
                "Macedonia del Norte",
                "Malta",
                "Mónaco",
                "Montenegro",
                "Noruega",
                "Países Bajos",
                "Polonia",
                "Portugal",
                "Reino Unido de Gran Bretaña e Irlanda del Norte",
                "República de Moldova",
                "Rumania",
                "San Marino",
                "Santa Sede",
                "Serbia",
                "Suecia",
                "Suiza",
                "Tayikistán",
                "Türkiye",
                "Turkmenistán",
                "Ucrania",
                "Uzbekistán",
                "Antigua y Barbuda",
                "Argentina",
                "Bahamas",
                "Barbados",
                "Belice",
                "Bolivia",
                "Brasil",
                "Canadá",
                "Chile",
                "Colombia",
                "Costa Rica",
                "Cuba",
                "Dominica",
                "Ecuador",
                "El Salvador",
                "Estados Unidos de América",
                "Granada",
                "Guatemala",
                "Guyana",
                "Haití",
                "Honduras",
                "Jamaica",
                "México",
                "Nicaragua",
                "Panamá",
                "Paraguay",
                "Perú",
                "República Dominicana",
                "Saint Kitts y Nevis",
                "San Vicente y las Granadinas",
                "Santa Lucía",
                "Suriname",
                "Trinidad y Tabago",
                "Uruguay",
                "Venezuela",
                "Angola",
                "Benin",
                "Botswana",
                "Burkina Faso",
                "Burundi",
                "Cabo Verde",
                "Camerún",
                "Chad",
                "Comoras",
                "Congo",
                "Côte d’Ivoire",
                "Djibouti",
                "Eritrea",
                "Eswatini",
                "Etiopía",
                "Gabón",
                "Gambia",
                "Ghana",
                "Guinea",
                "Guinea Ecuatorial",
                "Guinea-Bissau",
                "Kenya",
                "Lesotho",
                "Liberia",
                "Madagascar",
                "Malawi",
                "Malí",
                "Mauricio",
                "Mauritania",
                "Mozambique",
                "Namibia",
                "Níger",
                "Nigeria",
                "República Centroafricana",
                "República Democrática del Congo",
                "República Unida de Tanzanía",
                "Rwanda",
                "Santo Tomé y Príncipe",
                "Senegal",
                "Seychelles",
                "Sierra Leona",
                "Somalia",
                "Sudáfrica",
                "Sudán",
                "Sudán del Sur",
                "Togo",
                "Uganda",
                "Zambia",
                "Zimbabwe",
                "Arabia Saudita",
                "Argelia",
                "Bahrein",
                "Egipto",
                "Emiratos Árabes Unidos",
                "Estado de Palestina",
                "Irán",
                "Iraq",
                "Israel",
                "Jordania",
                "Kuwait",
                "Líbano",
                "Libia",
                "Marruecos",
                "Omán",
                "Qatar",
                "República Árabe Siria",
                "Túnez",
                "Yemen",
                "Otro"};
    }
}